### ISSUE TITLE
The teacher test SCORE for cora, citeseer, and PubMed are exceptionally low

### ISSUE THREAD

**Issue by PonderLY** [MIRALab-USTC/GraphAKD#1]
Hi, 

I have downloaded the teacher knowledge from the links provided in the codes but the teacher test scores are exceptionally low for Cora, Citeseer, and PubMed. My results are
For Cora, Teacher Test SCORE: 18.200%
For Citeseer, Teacher Test SCORE: 17.900%
For PubMed, Teacher Test SCORE: 36.200%

But for Arxiv, the results reported in the paper can be reproduced.

Could you please check the teacher knowledge provided on google drive?

**Comment by hhr114** [comment]
Hi, thanks for your attention.
As mentioned in `node-level/README.md`, DGL with a version later than 0.6.x will by default use `dgl.reorder_graph` to reorder the three citation networks, leading to a mismatch. Therefore, we suggest you follow the same environment as we do, which has been described in *Requirements*.
Btw, I have recently mentioned and fixed this bug of DGL in https://github.com/dmlc/dgl/issues/3987 and https://github.com/dmlc/dgl/pull/4104. You can either install the latest DGL from git.
