### ISSUE TITLE
关于代码问题

### ISSUE THREAD

**Issue by GorgeousMe** [MIRALab-USTC/GraphAKD#2]
https://github.com/MIRALab-USTC/GraphAKD/blob/3b4f8731c009ee4bbc09ff3ba65553f88da2e6ef/node-level/stu-gcn/train.py#L223-L257
1、这里第226行，将Discriminator.eval(),可为什么没有Discriminator_g.eval()
2、第224行：ad_gloss1 = loss_dis(fake_g, torch.ones_like(fake_g)) ，为什么第251行：ad_gloss2 = loss_dis(real_g, torch.ones_like(real_g)) + loss_dis(fake_g, torch.zeros_like(fake_g))，这是一个正向的优化逻辑，而不是ad_gloss2 = loss_dis(fake_g, torch.ones_like(fake_g))

**Comment by hhr114** [comment]
@GorgeousMe 你好，感谢指出代码中存在的问题，已经修改了相关bug，更新前后的结果对比如下（README中提供了用于复现的指令）
| Model                     | Dataset  | Pre-fixed   | Fixed       |
| ------------------------- | -------- | ----------- | ----------- |
| GCN with GraphAKD         | Cora     | 83.6 ±0.8   | 83.9 ±0.5   |
| GCN with GraphAKD         | CiteSeer | 72.9 ±0.4   | 72.9 ±0.4   |
| GCN with GraphAKD         | PubMed   | 81.3 ±0.4   | 81.5 ±0.5   |
| GCN with GraphAKD         | Flickr   | 52.95 ±0.24 | 52.72 ±0.18 |
| GCN with GraphAKD         | Arxiv    | 73.05 ±0.22 | 72.83 ±0.09 |
| GCN with GraphAKD         | Reddit   | 95.15 ±0.02 | 95.02 ±0.02 |
| Cluster-GCN with GraphAKD | Yelp     | 60.63 ±0.42 | 60.36 ±0.36 |
| Cluster-GCN with GraphAKD | Products | 81.45 ±0.47 | 81.72 ±0.32 |
| GCN with GraphAKD         | Molhiv   | 79.46 ±0.97 | 80.32 ±0.59 |
| GIN with GraphAKD         | Molhiv   | 79.16 ±1.50 | 80.52 ±0.49 |
| GCN with GraphAKD         | Molpcba  | 22.56 ±0.23 | 22.81 ±0.15 |
| GIN with GraphAKD         | Molpcba  | 25.85 ±0.17 | 25.73 ±0.12 |
