### ISSUE TITLE
The results of the citeseer dataset cannot be reproduced

### ISSUE THREAD

**Issue by Chrisable** [MIRALab-USTC/GraphAKD#4]
my experiment:
run 10 times:
```
Average val accuracy: 0.6954 ± 0.010432641084595956
Average test accuracy on citeseer: 0.6900999999999999 ± 0.009565040512198534
```
But paper reports:
 72.9 ±0.4

the seed i used are [2022,2023,.........2031]
Looking forward to your reply，thank you

**Comment by hhr114** [comment]
Thanks for your interest in our work. 
Please make sure your environment configuration is the same as ours, and so are the hyperparameters. 
Here are two sets of hyperparameters and the corresponding results. Hope it helps.
![image.png](https://pic5.58cdn.com.cn/nowater/webim/big/n_v245c56a4a57b6445ebec1283fd81b7c33.png)

![image.png](https://pic5.58cdn.com.cn/nowater/webim/big/n_v2c4c8b9a067d44a42aab1cb261132861a.png)

**Comment by Chrisable** [comment]
thank you
